###
GET http://localhost:8000/

###
POST http://localhost:8000/users/create_new_user/
content-type: application/json

{
    "username": "test_user_name6",
    "password": "test_user_password"
}

###
POST http://localhost:8000/users/login/
content-type: application/json

{
    "username": "test_user_name2",
    "password": "test_user_password"
}

###
GET http://localhost:8000/users/?include_deactivated=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjc0NDg3MzA5fQ.Qh0-gsq4X1zxfFPpVPD-zOVNWsenvpcz252SsthGhrI


###
GET http://localhost:8000/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjc0NDg3MzA5fQ.Qh0-gsq4X1zxfFPpVPD-zOVNWsenvpcz252SsthGhrI

###
PUT http://localhost:8000/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjc0NDg3MzA5fQ.Qh0-gsq4X1zxfFPpVPD-zOVNWsenvpcz252SsthGhrI
content-type: application/json

{
    "Email": "hell2o@example.com",
    "FirstName": "John2",
    "LastName": "Doe2",
    "Permissions": "total",
    "Username": "test_user_name3"
}